name: Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install dependencies
        run: |
          cd openai-moderation
          composer install
      - name: Build plugin
        run: |
          cd openai-moderation
          bash build.sh
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: openai-moderation
          path: openai-moderation/dist/openai-moderation-*.zip
